"""Install and uninstall built-in Claude Code hook wrappers.

The supported v0.1.7 integration is the optional UserPromptSubmit compile hook,
which returns structured additionalContext when local retrieval finds a match.

The older Stop-gate installer remains for compatibility but is not advertised as
a ready integration: current Claude Code provides last_assistant_message for the
just-finished turn and expects structured JSON for a visible warning, while that
wrapper retains its earlier transcript/stderr contract.

Both installers are idempotent, preserve unrelated hook entries, and refuse to
overwrite wrapper files they do not own.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

WRAPPER_MARKER = "# Auto-generated by `hermeneutic install-hook`"
WRAPPER_FILENAME = "hermeneutic-gate.py"

COMPILE_WRAPPER_MARKER = "# Auto-generated by `hermeneutic install-compile-hook`"
COMPILE_WRAPPER_FILENAME = "hermeneutic-compile.py"

COMPILE_WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
{marker}
"""hermeneutic UserPromptSubmit hook — compile layer (advisory mode).

Reads Claude Code UserPromptSubmit JSON, runs the user prompt through
`hermeneutic compile`, and emits structured `additionalContext` so Claude
Code injects the past-corrections preamble alongside the submitted prompt.
Always exits 0.
"""
import json, subprocess, sys

try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)

if not isinstance(payload, dict):
    sys.exit(0)
prompt = payload.get("prompt", "")
if not isinstance(prompt, str) or not prompt.strip():
    sys.exit(0)

try:
    proc = subprocess.run(
        [sys.executable, "-m", "hermeneutic.cli", "compile"],
        input=prompt, capture_output=True, text=True, timeout=4,
    )
except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
    sys.exit(0)

preamble = (proc.stdout or "").strip()
if proc.returncode == 0 and preamble:
    print(json.dumps({{
        "hookSpecificOutput": {{
            "hookEventName": "UserPromptSubmit",
            "additionalContext": preamble,
        }}
    }}))
sys.exit(0)
'''


WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
{marker}
"""Compatibility-only hermeneutic Stop-hook wrapper (unsupported in v0.1.7).

Reads Claude Code Stop hook stdin JSON, extracts the last assistant turn
from the transcript JSONL, pipes it through `hermeneutic gate`, and writes
a one-line notice to stderr if RISK fires. This historical transcript/stderr
path is not a supported current-host warning contract. Always exits 0.
"""
import json, subprocess, sys
from pathlib import Path

try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)

transcript = payload.get("transcript_path", "")
if not transcript or not Path(transcript).is_file():
    sys.exit(0)

# Walk transcript bottom-up to find last assistant turn with text content.
last_text = ""
try:
    with open(transcript, encoding="utf-8") as f:
        for line in reversed(f.readlines()):
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("type") != "assistant":
                continue
            msg = d.get("content") or d.get("message") or {{}}
            content = msg.get("content", "") if isinstance(msg, dict) else ""
            if isinstance(content, list):
                parts = [b.get("text", "") for b in content
                         if isinstance(b, dict) and b.get("type") == "text"]
                last_text = "\\n".join(p for p in parts if p)
            elif isinstance(content, str):
                last_text = content
            if last_text.strip():
                break
except OSError:
    sys.exit(0)

if not last_text.strip():
    sys.exit(0)

# Pipe through hermeneutic gate. Use python -m to avoid PATH issues at hook-fire time.
try:
    proc = subprocess.run(
        [sys.executable, "-m", "hermeneutic.cli", "gate"],
        input=last_text, capture_output=True, text=True, timeout=5,
    )
except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
    sys.exit(0)

if proc.returncode != 0 and proc.stdout.strip():
    print(f"[hermeneutic] {{proc.stdout.splitlines()[0]}}", file=sys.stderr)

sys.exit(0)  # advisory only — never block
'''


class InstallError(Exception):
    """Raised when install/uninstall cannot proceed safely."""


def _claude_dir(home: Path | None = None) -> Path:
    """Return ~/.claude/ (overridable via $HOME for tests)."""
    h = home if home is not None else Path(os.environ.get("HOME", "~")).expanduser()
    return h / ".claude"


def _hooks_dir(home: Path | None = None) -> Path:
    return _claude_dir(home) / "hooks"


def _settings_path(home: Path | None = None) -> Path:
    return _claude_dir(home) / "settings.json"


def _wrapper_path(home: Path | None = None) -> Path:
    return _hooks_dir(home) / WRAPPER_FILENAME


def _is_our_wrapper(path: Path) -> bool:
    """Detect our marker in the first 5 lines of an existing file."""
    if not path.is_file():
        return False
    try:
        with open(path, encoding="utf-8") as f:
            head = "".join(f.readline() for _ in range(5))
        return WRAPPER_MARKER in head
    except OSError:
        return False


def _hook_already_registered(settings: dict) -> bool:
    """Fingerprint: does any Stop hook entry's command reference our wrapper?"""
    stop_entries = settings.get("hooks", {}).get("Stop", []) or []
    for entry in stop_entries:
        for h in entry.get("hooks", []):
            if WRAPPER_FILENAME in h.get("command", ""):
                return True
    return False


def _new_hook_entry(wrapper_abspath: Path) -> dict:
    return {
        "hooks": [
            {
                "type": "command",
                "command": f"python3 {wrapper_abspath}",
                "timeout": 5,
            }
        ]
    }


def install(home: Path | None = None) -> dict:
    """Install the Stop hook. Returns a status dict.

    Returns: {
      "wrapper_path": str,
      "wrapper_state": "created" | "updated" | "preserved-foreign",
      "settings_state": "added" | "already-present" | "no-change",
    }
    """
    claude = _claude_dir(home)
    if not claude.is_dir():
        raise InstallError(
            f"Claude Code config dir not found at {claude}. "
            "Install Claude Code first, then re-run."
        )

    hooks = _hooks_dir(home)
    hooks.mkdir(parents=True, exist_ok=True)

    wrapper = _wrapper_path(home)
    # Wrapper file management
    if wrapper.is_file() and not _is_our_wrapper(wrapper):
        raise InstallError(
            f"Refusing to overwrite existing file at {wrapper} "
            "(no hermeneutic marker found). Rename it or remove it manually."
        )
    wrapper_state = "updated" if wrapper.is_file() else "created"
    wrapper.write_text(WRAPPER_TEMPLATE.format(marker=WRAPPER_MARKER), encoding="utf-8")
    wrapper.chmod(0o755)

    # Settings file management
    settings_path = _settings_path(home)
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError as e:
            raise InstallError(
                f"settings.json at {settings_path} is malformed JSON ({e}). "
                "Fix it manually, then re-run."
            ) from e
    else:
        settings = {}

    if _hook_already_registered(settings):
        settings_state = "already-present"
    else:
        settings.setdefault("hooks", {}).setdefault("Stop", [])
        settings["hooks"]["Stop"].append(_new_hook_entry(wrapper.resolve()))
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "added"

    return {
        "wrapper_path": str(wrapper),
        "wrapper_state": wrapper_state,
        "settings_state": settings_state,
    }


def install_compile(home: Path | None = None) -> dict:
    """Install the UserPromptSubmit hook for the compile layer.

    Same idempotency + foreign-file protections as install(); different
    wrapper file and different hook event (UserPromptSubmit vs Stop).
    """
    claude = _claude_dir(home)
    if not claude.is_dir():
        raise InstallError(
            f"Claude Code config dir not found at {claude}. "
            "Install Claude Code first, then re-run."
        )

    settings_path = _settings_path(home)
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError as e:
            raise InstallError(
                f"settings.json at {settings_path} is malformed JSON ({e})."
            ) from e
        if not _compile_settings_shape_valid(settings):
            raise InstallError(
                f"settings.json at {settings_path} has an invalid hook structure."
            )
    else:
        settings = {}

    hooks = _hooks_dir(home)
    wrapper = hooks / COMPILE_WRAPPER_FILENAME
    if wrapper.is_file() and not _file_has_marker(wrapper, COMPILE_WRAPPER_MARKER):
        raise InstallError(
            f"Refusing to overwrite existing file at {wrapper} "
            "(no hermeneutic compile-hook marker found). Rename it or remove it manually."
        )

    hooks.mkdir(parents=True, exist_ok=True)
    wrapper_state = "updated" if wrapper.is_file() else "created"
    wrapper.write_text(COMPILE_WRAPPER_TEMPLATE.format(marker=COMPILE_WRAPPER_MARKER), encoding="utf-8")
    wrapper.chmod(0o755)
    wrapper_abspath = wrapper.resolve()

    settings_state = _normalize_compile_hook_registration(settings, wrapper_abspath)
    if settings_state == "absent":
        settings.setdefault("hooks", {}).setdefault("UserPromptSubmit", [])
        settings["hooks"]["UserPromptSubmit"].append({
            "hooks": [{
                "type": "command",
                "command": sys.executable,
                "args": [str(wrapper_abspath)],
                "timeout": 5,
            }]
        })
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "added"
    elif settings_state == "migrated":
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")

    return {
        "wrapper_path": str(wrapper),
        "wrapper_state": wrapper_state,
        "settings_state": settings_state,
    }


def uninstall_compile(home: Path | None = None) -> dict:
    wrapper = _hooks_dir(home) / COMPILE_WRAPPER_FILENAME
    settings_path = _settings_path(home)
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            return {
                "wrapper_state": "preserved" if wrapper.is_file() else "absent",
                "settings_state": "malformed",
            }
        if not _compile_settings_shape_valid(settings):
            return {
                "wrapper_state": "preserved" if wrapper.is_file() else "absent",
                "settings_state": "malformed",
            }
    else:
        settings = None

    settings_removed = False
    if settings is not None:
        ups = settings.get("hooks", {}).get("UserPromptSubmit", []) or []
        filtered: list[dict] = []
        for entry in ups:
            handlers = entry.get("hooks", [])
            kept = [h for h in handlers if not _compile_handler_registered(h, wrapper.resolve())]
            if len(kept) != len(handlers):
                settings_removed = True
            if kept:
                entry["hooks"] = kept
                filtered.append(entry)
        if settings_removed:
            settings["hooks"]["UserPromptSubmit"] = filtered
            settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")

    if not wrapper.is_file():
        wrapper_state = "absent"
    elif _file_has_marker(wrapper, COMPILE_WRAPPER_MARKER):
        wrapper.unlink()
        wrapper_state = "removed"
    else:
        wrapper_state = "preserved-foreign"

    return {
        "wrapper_state": wrapper_state,
        "settings_state": "removed" if settings_removed else "absent",
    }


def _file_has_marker(path: Path, marker: str) -> bool:
    if not path.is_file():
        return False
    try:
        with open(path, encoding="utf-8") as f:
            head = "".join(f.readline() for _ in range(5))
        return marker in head
    except OSError:
        return False


def _compile_handler_registered(handler: dict, wrapper_abspath: Path) -> bool:
    """Match our exec-form handler or the exact shell form shipped previously."""
    path = str(wrapper_abspath)
    args = handler.get("args")
    if isinstance(args, list) and args == [path]:
        return True
    command = handler.get("command", "")
    return command in {f"python3 {path}", f"{sys.executable} {path}"}


def _compile_settings_shape_valid(settings: object) -> bool:
    """Accept absent compile-hook keys, but reject structures we cannot preserve safely."""
    if not isinstance(settings, dict):
        return False
    hooks = settings.get("hooks", {})
    if not isinstance(hooks, dict):
        return False
    entries = hooks.get("UserPromptSubmit", [])
    if entries is None:
        entries = []
    if not isinstance(entries, list):
        return False
    for entry in entries:
        if not isinstance(entry, dict):
            return False
        handlers = entry.get("hooks", [])
        if handlers is None:
            handlers = []
        if not isinstance(handlers, list) or any(not isinstance(handler, dict) for handler in handlers):
            return False
    return True


def _normalize_compile_hook_registration(settings: dict, wrapper_abspath: Path) -> str:
    """Return absent/already-present, migrating an exact older registration in place."""
    ups = settings.get("hooks", {}).get("UserPromptSubmit", []) or []
    found = False
    changed = False
    path = str(wrapper_abspath)
    for entry in ups:
        for h in entry.get("hooks", []):
            args = h.get("args")
            command = h.get("command", "")
            if args == [path]:
                found = True
            elif command in {f"python3 {path}", f"{sys.executable} {path}"}:
                found = True
                h["args"] = [path]
                changed = True
            else:
                continue

            expected = {
                "type": "command",
                "command": sys.executable,
                "args": [path],
                "timeout": 5,
            }
            for key, value in expected.items():
                if h.get(key) != value:
                    h[key] = value
                    changed = True

    if changed:
        return "migrated"
    return "already-present" if found else "absent"


def uninstall(home: Path | None = None) -> dict:
    """Remove the Stop hook. Returns a status dict.

    Returns: {
      "wrapper_state": "removed" | "preserved-foreign" | "absent",
      "settings_state": "removed" | "absent",
    }
    """
    wrapper = _wrapper_path(home)

    # Wrapper file removal
    if not wrapper.is_file():
        wrapper_state = "absent"
    elif _is_our_wrapper(wrapper):
        wrapper.unlink()
        wrapper_state = "removed"
    else:
        wrapper_state = "preserved-foreign"

    # Settings file cleanup
    settings_path = _settings_path(home)
    if not settings_path.is_file():
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}

    try:
        settings = json.loads(settings_path.read_text())
    except json.JSONDecodeError:
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}

    stop_entries = settings.get("hooks", {}).get("Stop", []) or []
    filtered: list[dict] = []
    removed_any = False
    for entry in stop_entries:
        kept_hooks = [
            h for h in entry.get("hooks", [])
            if WRAPPER_FILENAME not in h.get("command", "")
        ]
        if len(kept_hooks) != len(entry.get("hooks", [])):
            removed_any = True
        if kept_hooks:
            entry["hooks"] = kept_hooks
            filtered.append(entry)
        # Drop entries whose hooks list is now empty.

    if removed_any:
        settings["hooks"]["Stop"] = filtered
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "removed"
    else:
        settings_state = "absent"

    return {"wrapper_state": wrapper_state, "settings_state": settings_state}
