"""Install / uninstall a Claude Code Stop hook that runs `hermeneutic gate`
on every assistant turn (advisory mode — never blocks).

Real-time gating in two commands:

    pip install hermeneutic
    hermeneutic install-hook
    # Restart Claude Code.

Idempotent: re-running install-hook is safe (won't double-write).
Uninstall: `hermeneutic uninstall-hook` removes our entries cleanly,
preserves any other Stop hooks the user has configured.

Verified against real Claude Code Stop and PostToolUse hook implementations:
hooks receive `{"transcript_path", "session_id"}` JSON on stdin, not env vars.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

WRAPPER_MARKER = "# Auto-generated by `hermeneutic install-hook`"
WRAPPER_FILENAME = "hermeneutic-gate.py"

COMPILE_WRAPPER_MARKER = "# Auto-generated by `hermeneutic install-compile-hook`"
COMPILE_WRAPPER_FILENAME = "hermeneutic-compile.py"

COMPILE_WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
{marker}
"""hermeneutic UserPromptSubmit hook — compile layer (advisory mode).

Reads Claude Code UserPromptSubmit JSON, runs the user prompt through
`hermeneutic compile`, and emits {{"systemMessage": "<preamble>"}} so
Claude Code injects the past-corrections preamble ahead of the model.
Always exits 0.
"""
import json, subprocess, sys

try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)

prompt = payload.get("prompt", "")
if not prompt or not prompt.strip():
    sys.exit(0)

try:
    proc = subprocess.run(
        [sys.executable, "-m", "hermeneutic.cli", "compile"],
        input=prompt, capture_output=True, text=True, timeout=4,
    )
except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
    sys.exit(0)

preamble = (proc.stdout or "").strip()
if preamble:
    print(json.dumps({{"systemMessage": preamble}}))
sys.exit(0)
'''


WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
{marker}
"""hermeneutic Stop-hook wrapper — advisory mode (never blocks).

Reads Claude Code Stop hook stdin JSON, extracts the last assistant turn
from the transcript JSONL, pipes it through `hermeneutic gate`, and writes
a one-line notice to stderr if RISK fires (Claude Code surfaces stderr in
the UI). Always exits 0.
"""
import json, subprocess, sys
from pathlib import Path

try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)

transcript = payload.get("transcript_path", "")
if not transcript or not Path(transcript).is_file():
    sys.exit(0)

# Walk transcript bottom-up to find last assistant turn with text content.
last_text = ""
try:
    with open(transcript, encoding="utf-8") as f:
        for line in reversed(f.readlines()):
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            if d.get("type") != "assistant":
                continue
            msg = d.get("content") or d.get("message") or {{}}
            content = msg.get("content", "") if isinstance(msg, dict) else ""
            if isinstance(content, list):
                parts = [b.get("text", "") for b in content
                         if isinstance(b, dict) and b.get("type") == "text"]
                last_text = "\\n".join(p for p in parts if p)
            elif isinstance(content, str):
                last_text = content
            if last_text.strip():
                break
except OSError:
    sys.exit(0)

if not last_text.strip():
    sys.exit(0)

# Pipe through hermeneutic gate. Use python -m to avoid PATH issues at hook-fire time.
try:
    proc = subprocess.run(
        [sys.executable, "-m", "hermeneutic.cli", "gate"],
        input=last_text, capture_output=True, text=True, timeout=5,
    )
except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
    sys.exit(0)

if proc.returncode != 0 and proc.stdout.strip():
    print(f"[hermeneutic] {{proc.stdout.splitlines()[0]}}", file=sys.stderr)

sys.exit(0)  # advisory only — never block
'''


class InstallError(Exception):
    """Raised when install/uninstall cannot proceed safely."""


def _claude_dir(home: Path | None = None) -> Path:
    """Return ~/.claude/ (overridable via $HOME for tests)."""
    h = home if home is not None else Path(os.environ.get("HOME", "~")).expanduser()
    return h / ".claude"


def _hooks_dir(home: Path | None = None) -> Path:
    return _claude_dir(home) / "hooks"


def _settings_path(home: Path | None = None) -> Path:
    return _claude_dir(home) / "settings.json"


def _wrapper_path(home: Path | None = None) -> Path:
    return _hooks_dir(home) / WRAPPER_FILENAME


def _is_our_wrapper(path: Path) -> bool:
    """Detect our marker in the first 5 lines of an existing file."""
    if not path.is_file():
        return False
    try:
        with open(path, encoding="utf-8") as f:
            head = "".join(f.readline() for _ in range(5))
        return WRAPPER_MARKER in head
    except OSError:
        return False


def _hook_already_registered(settings: dict) -> bool:
    """Fingerprint: does any Stop hook entry's command reference our wrapper?"""
    stop_entries = settings.get("hooks", {}).get("Stop", []) or []
    for entry in stop_entries:
        for h in entry.get("hooks", []):
            if WRAPPER_FILENAME in h.get("command", ""):
                return True
    return False


def _new_hook_entry(wrapper_abspath: Path) -> dict:
    return {
        "hooks": [
            {
                "type": "command",
                "command": f"python3 {wrapper_abspath}",
                "timeout": 5,
            }
        ]
    }


def install(home: Path | None = None) -> dict:
    """Install the Stop hook. Returns a status dict.

    Returns: {
      "wrapper_path": str,
      "wrapper_state": "created" | "updated" | "preserved-foreign",
      "settings_state": "added" | "already-present" | "no-change",
    }
    """
    claude = _claude_dir(home)
    if not claude.is_dir():
        raise InstallError(
            f"Claude Code config dir not found at {claude}. "
            "Install Claude Code first, then re-run."
        )

    hooks = _hooks_dir(home)
    hooks.mkdir(parents=True, exist_ok=True)

    wrapper = _wrapper_path(home)
    # Wrapper file management
    if wrapper.is_file() and not _is_our_wrapper(wrapper):
        raise InstallError(
            f"Refusing to overwrite existing file at {wrapper} "
            "(no hermeneutic marker found). Rename it or remove it manually."
        )
    wrapper_state = "updated" if wrapper.is_file() else "created"
    wrapper.write_text(WRAPPER_TEMPLATE.format(marker=WRAPPER_MARKER), encoding="utf-8")
    wrapper.chmod(0o755)

    # Settings file management
    settings_path = _settings_path(home)
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError as e:
            raise InstallError(
                f"settings.json at {settings_path} is malformed JSON ({e}). "
                "Fix it manually, then re-run."
            ) from e
    else:
        settings = {}

    if _hook_already_registered(settings):
        settings_state = "already-present"
    else:
        settings.setdefault("hooks", {}).setdefault("Stop", [])
        settings["hooks"]["Stop"].append(_new_hook_entry(wrapper.resolve()))
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "added"

    return {
        "wrapper_path": str(wrapper),
        "wrapper_state": wrapper_state,
        "settings_state": settings_state,
    }


def install_compile(home: Path | None = None) -> dict:
    """Install the UserPromptSubmit hook for the compile layer.

    Same idempotency + foreign-file protections as install(); different
    wrapper file and different hook event (UserPromptSubmit vs Stop).
    """
    claude = _claude_dir(home)
    if not claude.is_dir():
        raise InstallError(
            f"Claude Code config dir not found at {claude}. "
            "Install Claude Code first, then re-run."
        )
    hooks = _hooks_dir(home)
    hooks.mkdir(parents=True, exist_ok=True)

    wrapper = hooks / COMPILE_WRAPPER_FILENAME
    if wrapper.is_file() and not _file_has_marker(wrapper, COMPILE_WRAPPER_MARKER):
        raise InstallError(
            f"Refusing to overwrite existing file at {wrapper} "
            "(no hermeneutic compile-hook marker found). Rename it or remove it manually."
        )
    wrapper_state = "updated" if wrapper.is_file() else "created"
    wrapper.write_text(COMPILE_WRAPPER_TEMPLATE.format(marker=COMPILE_WRAPPER_MARKER), encoding="utf-8")
    wrapper.chmod(0o755)

    settings_path = _settings_path(home)
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError as e:
            raise InstallError(
                f"settings.json at {settings_path} is malformed JSON ({e})."
            ) from e
    else:
        settings = {}

    if _compile_hook_already_registered(settings):
        settings_state = "already-present"
    else:
        settings.setdefault("hooks", {}).setdefault("UserPromptSubmit", [])
        settings["hooks"]["UserPromptSubmit"].append({
            "hooks": [{
                "type": "command",
                "command": f"python3 {wrapper.resolve()}",
                "timeout": 5,
            }]
        })
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "added"

    return {
        "wrapper_path": str(wrapper),
        "wrapper_state": wrapper_state,
        "settings_state": settings_state,
    }


def uninstall_compile(home: Path | None = None) -> dict:
    wrapper = _hooks_dir(home) / COMPILE_WRAPPER_FILENAME
    if not wrapper.is_file():
        wrapper_state = "absent"
    elif _file_has_marker(wrapper, COMPILE_WRAPPER_MARKER):
        wrapper.unlink()
        wrapper_state = "removed"
    else:
        wrapper_state = "preserved-foreign"

    settings_path = _settings_path(home)
    if not settings_path.is_file():
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}
    try:
        settings = json.loads(settings_path.read_text())
    except json.JSONDecodeError:
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}

    ups = settings.get("hooks", {}).get("UserPromptSubmit", []) or []
    filtered: list[dict] = []
    removed = False
    for entry in ups:
        kept = [h for h in entry.get("hooks", []) if COMPILE_WRAPPER_FILENAME not in h.get("command", "")]
        if len(kept) != len(entry.get("hooks", [])):
            removed = True
        if kept:
            entry["hooks"] = kept
            filtered.append(entry)
    if removed:
        settings["hooks"]["UserPromptSubmit"] = filtered
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        return {"wrapper_state": wrapper_state, "settings_state": "removed"}
    return {"wrapper_state": wrapper_state, "settings_state": "absent"}


def _file_has_marker(path: Path, marker: str) -> bool:
    if not path.is_file():
        return False
    try:
        with open(path, encoding="utf-8") as f:
            head = "".join(f.readline() for _ in range(5))
        return marker in head
    except OSError:
        return False


def _compile_hook_already_registered(settings: dict) -> bool:
    ups = settings.get("hooks", {}).get("UserPromptSubmit", []) or []
    for entry in ups:
        for h in entry.get("hooks", []):
            if COMPILE_WRAPPER_FILENAME in h.get("command", ""):
                return True
    return False


def uninstall(home: Path | None = None) -> dict:
    """Remove the Stop hook. Returns a status dict.

    Returns: {
      "wrapper_state": "removed" | "preserved-foreign" | "absent",
      "settings_state": "removed" | "absent",
    }
    """
    wrapper = _wrapper_path(home)

    # Wrapper file removal
    if not wrapper.is_file():
        wrapper_state = "absent"
    elif _is_our_wrapper(wrapper):
        wrapper.unlink()
        wrapper_state = "removed"
    else:
        wrapper_state = "preserved-foreign"

    # Settings file cleanup
    settings_path = _settings_path(home)
    if not settings_path.is_file():
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}

    try:
        settings = json.loads(settings_path.read_text())
    except json.JSONDecodeError:
        return {"wrapper_state": wrapper_state, "settings_state": "absent"}

    stop_entries = settings.get("hooks", {}).get("Stop", []) or []
    filtered: list[dict] = []
    removed_any = False
    for entry in stop_entries:
        kept_hooks = [
            h for h in entry.get("hooks", [])
            if WRAPPER_FILENAME not in h.get("command", "")
        ]
        if len(kept_hooks) != len(entry.get("hooks", [])):
            removed_any = True
        if kept_hooks:
            entry["hooks"] = kept_hooks
            filtered.append(entry)
        # Drop entries whose hooks list is now empty.

    if removed_any:
        settings["hooks"]["Stop"] = filtered
        settings_path.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        settings_state = "removed"
    else:
        settings_state = "absent"

    return {"wrapper_state": wrapper_state, "settings_state": settings_state}
